version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
    open-pull-requests-limit: 20
    labels:
      - 'dependencies'
    groups:
      first-party-actions:
        patterns:
          - 'actions/*'
      third-party-actions:
        exclude-patterns:
          - 'actions/*'
